const data = {
    products: [
        {
            _id: '1',
            name: 'Demetra Ruched Crop Top White',
            category: 'Crop top',
            image: '/images/p1.jpg',
            price: '29.99$',
            brand: 'Mochi',
            rating: 5,
            numReviews: 10,
            description: 'High quality handmade top',
        },
        {
            _id: '2',
            name: 'Demetra Ruched Crop Top Red',
            category: 'Crop top',
            image: '/images/p2.jpg',
            price: '29.99$',
            brand: 'Mochi',
            rating: 5,
            numReviews: 10,
            description: 'High quality handmade top',
        },
        {
            _id: '3',
            name: 'Demetra Ruched Crop Top Light Blue',
            category: 'Crop top',
            image: '/images/p3.jpg',
            price: '29.99$',
            brand: 'Mochi',
            rating: 5,
            numReviews: 10,
            description: 'High quality handmade top',
        },
        {
            _id: '4',
            name: 'Demetra Ruched Crop Top Lilac',
            category: 'Crop top',
            image: '/images/p4.jpg',
            price: '29.99$',
            brand: 'Mochi',
            rating: 5,
            numReviews: 10,
            description: 'High quality handmade top',
        },
        {
            _id: '5',
            name: 'Demetra Ruched Crop Top Gold',
            category: 'Crop top',
            image: '/images/p5.jpg',
            price: '29.99$',
            brand: 'Mochi',
            rating: 5,
            numReviews: 10,
            description: 'High quality handmade top',
        },
        {
            _id: '6',
            name: 'Demetra Ruched Crop Top Black',
            category: 'Crop top',
            image: '/images/p6.jpg',
            price: '29.99$',
            brand: 'Mochi',
            rating: 5,
            numReviews: 10,
            description: 'High quality handmade top',
        },
    ],
};
export default data ;